### ISSUE TITLE
SessionImpl#removeHeartBeat is not fully testable

### ISSUE THREAD

**Issue by Minification** [ThorbenKuck/NetCom2#17]
# Description
It is currently not possible to fully test the `removeHeartBeat` method in `SessionImpl`.
More specifically, the case where the retrieved heartbeat is equal to `null` can not be tested.

This is because it is currently impossible to insert `null` heartbeats into the internal `Map`, due to `addHeartBeat` calling a method on the passed in heartbeat. 

Thus, a NullPointerException is thrown upon trying to insert a `null` value, which in turn makes it impossible to test the `null` case for `removeHeartBeat`.

# In Code
Line 155 is where the NPE occurs:
```java
@Override
public void addHeartBeat(final HeartBeat<Session> heartBeat) {
	heartBeats.add(heartBeat);
	heartBeat.parallel().run(this);      <--
}
```

And line 164 is where the test case cannot be tested:
```java
@Override
public void removeHeartBeat(final HeartBeat<Session> heartBeat) {
	final HeartBeat<Session> heartBeat1 = heartBeats.remove(heartBeats.indexOf(heartBeat));
	if (heartBeat1 != null) {     <--
		heartBeat1.stop();
	}
}
```

**Comment by ThorbenKuck** [comment]
This Issue will now be closed and labled "wontfix".

Reason: Null is not a valid parameter. The real issue is, that NetCom2Utils.parameterNotNull is missing.
The same is true for removeHeartBeat
